// <auto-generated />
namespace MyFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterForm3ReportTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterForm3ReportTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202103221805180_AlterForm3ReportTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
