// <auto-generated />
namespace MyFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddForm5Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddForm5Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202103272342026_AddForm5Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
