// <auto-generated />
namespace MyFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterForm4A : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterForm4A));
        
        string IMigrationMetadata.Id
        {
            get { return "202103270234281_AlterForm4A"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
